version: "3.9"

services:
  sync-db:
    image: mongo:latest
    volumes:
      - ./db:/data/db
    network_mode: host
    command: "mongod --port 27018"
    logging:
      driver: none
  sync-api:
    image: sync-api:latest
    env_file:
      - ./.dev.env
    volumes:
      - ./src:/api/src
    command: npm run dev
    network_mode: host
    depends_on:
      - sync-db
