version: "3.9"

services:
  db-template:
    image: mongo:latest
    volumes:
      - ./db:/data/db
    network_mode: host
    command: 'mongod --port 27018'
    logging:
      driver: none
  backend-template:
    image: backend-template:latest
    environment:
      - NODE_ENV=development # environment type
      - PORT=5000 # server port
      - MONGODB_URI=mongodb://localhost:27018/templatedb # db connection
      - ORIGINS_WHITELIST=http://localhost:5000,http://[::]:5000 # server cors origins
      - PASSWORD_ENCRYPTION_ITERATIONS=10000 #number of the iteration that the encryption algo will use
      - PASSWORD_ENCRYPTION_OUTPUT_LENGTH=64 #the length of the salt in bytes that is used to encrypt the password
      - PASSWORD_ENCRYPTION_SALT_BYTE_LENGTH=32 #the length of the salt in bytes that is used to encrypt the password
      - SESSION_COOKIE_SECRET=super doper secret #the secret used to encrypt the cookie
      - SESSION_COOKIE_MAXAGE=86400000 #the max age of the session cookie that is Equals 1 day (1 day * 24 hr/1 day * 60 min/1 hr * 60 sec/1 min * 1000 ms / 1 sec)
      - SESSION_MONGODB_URL=mongodb://localhost:27018/templatedb #database link used for session
      - SESSION_MONGODB_COLLECTION_NAME=sessions #collection name that is used for sessions
    volumes:
      - ./backend/src:/backend/src
    command: npm run dev
    network_mode: host
    depends_on:
      - db-template
