# Using official node runtime base image
FROM node:14-alpine

# Set the application directory
WORKDIR /api

# Copy package.json
COPY package.json package.json

# Install dependancies
RUN npm install --only=prod

# Copy code to /src
COPY src src

# Define our command to be run when launching the container
CMD ["npm", "run", "start"]